SERVICE_ACCOUNT_KEY_PATH = "serviceAccountKey.json"


USER_COLLECTION = "User"
EXERCICIO_COLLECTION = "Exercicio"
USER_EXERCICIO_COLLECTION = "UserExercicio"
SONO_COLLECTION = "Sono"
MEDICACAO_COLLECTION = "Medicacao"
DOR_COLLECTION = "Dor"


USER_REFERENCE_FIELD = "UserID"


USER_ID_FIELD = "UserID"
USER_NAME_FIELD = "nome"
USER_AGE_FIELD = "idade"
USER_EMAIL_FIELD = "email"
USER_PHOTO_FIELD = "userPhoto"

SONO_ID_FIELD = "sonoID"
SONO_QUALIDADE_FIELD = "qualidade"
SONO_DESPERTARES_FIELD = "despertaresNoturnos"
SONO_HORAS_FIELD = "horasSono"


MEDICACAO_ID_FIELD = "medicacaoID"
MEDICACAO_HABITUAL_FIELD = "medicacaoHabitual"
MEDICACAO_SOS_FIELD = "medicacaoSOS"
MEDICACAO_QUANTIDADE_FIELD = "quantidade"
MEDICACAO_HORARIO_FIELD = "horarioToma"


DOR_ID_FIELD = "dorID"
DOR_LOCALIZACAO_FIELD = "localizacao"
DOR_INTENSIDADE_FIELD = "intensidade"


EXERCICIO_ID_FIELD = "ExercicioID"
EXERCICIO_DIFICULDADE_FIELD = "dificuldade"
EXERCICIO_CONCLUSAO_FIELD = "conclusao"
EXERCICIO_QUALIDADE_FIELD = "qualidadeExecucao"


USER_EXERCICIO_ID_FIELD = "UserExercicioID"
EXERCICIO_REFERENCE_FIELD = "ExercicioID"